const REGISTER_USER = 'REGISTER_USER';
const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const CREATE_POST = 'CREATE_POST';
const EDIT_POST = 'EDIT_POST';
const COMMENT_POST = 'COMMENT_POST';
const ERROR_MESSAGE = 'ERROR_MESSAGE';

export {
      REGISTER_USER,
      LOGIN_USER,
      LOGOUT_USER,
      CREATE_POST,
      EDIT_POST,
      COMMENT_POST,
      ERROR_MESSAGE
};